# CMake generated Testfile for 
# Source directory: /home/xzl/work/fcitx5/fcitx5/test
# Build directory: /home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testdbusmessage "/home/xzl/work/fcitx5/fcitx5/test/dbus_wrapper.sh" "/usr/bin/dbus-daemon" "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testdbusmessage")
set_tests_properties(testdbusmessage PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;52;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testdbus "/home/xzl/work/fcitx5/fcitx5/test/dbus_wrapper.sh" "/usr/bin/dbus-daemon" "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testdbus")
set_tests_properties(testdbus PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;52;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testservicewatcher "/home/xzl/work/fcitx5/fcitx5/test/dbus_wrapper.sh" "/usr/bin/dbus-daemon" "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testservicewatcher")
set_tests_properties(testservicewatcher PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;52;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testflags "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testflags")
set_tests_properties(testflags PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(teststringutils "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/teststringutils")
set_tests_properties(teststringutils PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testkey "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testkey")
set_tests_properties(testkey PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testutf8 "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testutf8")
set_tests_properties(testutf8 PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testcolor "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testcolor")
set_tests_properties(testcolor PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testi18nstring "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testi18nstring")
set_tests_properties(testi18nstring PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testevent "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testevent")
set_tests_properties(testevent PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testlist "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testlist")
set_tests_properties(testlist PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testfs "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testfs")
set_tests_properties(testfs PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testlibrary "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testlibrary")
set_tests_properties(testlibrary PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(teststandardpath "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/teststandardpath")
set_tests_properties(teststandardpath PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testunixfd "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testunixfd")
set_tests_properties(testunixfd PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testmetastring "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testmetastring")
set_tests_properties(testmetastring PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testhandlertable "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testhandlertable")
set_tests_properties(testhandlertable PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testsignals "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testsignals")
set_tests_properties(testsignals PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testinputbuffer "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testinputbuffer")
set_tests_properties(testinputbuffer PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testlog "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testlog")
set_tests_properties(testlog PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testeventdispatcher "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testeventdispatcher")
set_tests_properties(testeventdispatcher PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testrect "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testrect")
set_tests_properties(testrect PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testfallbackuuid "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testfallbackuuid")
set_tests_properties(testfallbackuuid PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testsemver "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testsemver")
set_tests_properties(testsemver PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;61;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testconfig "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testconfig")
set_tests_properties(testconfig PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;76;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testconfigdbus "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testconfigdbus")
set_tests_properties(testconfigdbus PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;76;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testinputcontext "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testinputcontext")
set_tests_properties(testinputcontext PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testsurroundingtext "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testsurroundingtext")
set_tests_properties(testsurroundingtext PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testaddon "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testaddon")
set_tests_properties(testaddon PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testmenu "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testmenu")
set_tests_properties(testmenu PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testuserinterfacemanager "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testuserinterfacemanager")
set_tests_properties(testuserinterfacemanager PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testelement "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testelement")
set_tests_properties(testelement PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testcandidatelist "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testcandidatelist")
set_tests_properties(testcandidatelist PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testicontheme "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testicontheme")
set_tests_properties(testicontheme PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testtext "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testtext")
set_tests_properties(testtext PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testinstance "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testinstance")
set_tests_properties(testinstance PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;95;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testxkbrules "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testxkbrules")
set_tests_properties(testxkbrules PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;106;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testisocodes "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testisocodes")
set_tests_properties(testisocodes PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;112;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testcompose "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testcompose")
set_tests_properties(testcompose PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;116;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testemoji "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testemoji")
set_tests_properties(testemoji PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;123;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testunicode "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testunicode")
set_tests_properties(testunicode PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;129;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testspell "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testspell")
set_tests_properties(testspell PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;136;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
add_test(testquickphrase "/home/xzl/work/fcitx5/fcitx5/obj-x86_64-linux-gnu/test/testquickphrase")
set_tests_properties(testquickphrase PROPERTIES  _BACKTRACE_TRIPLES "/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;142;add_test;/home/xzl/work/fcitx5/fcitx5/test/CMakeLists.txt;0;")
subdirs("addon")
